
services:

  app:
    build: .
    container_name: gai-registry-app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    networks:
      - app_network

  db:
    container_name: GuardDB
    image: bitnamilegacy/postgresql:17.6.0
    env_file:
      - ./.env    
    environment:  
      POSTGRES_USER : ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - ./conf/db_init.sql:/docker-entrypoint-initdb.d/init.sql      
      - ./pgdata:/var/lib/postgresql/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - app_network


networks:
  app_network:
    driver: bridge


volumes:
  pgdata: 